name: Deploy AWS Lambda Functions

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install Serverless Framework CLI
      - name: Install Serverless
        run: npm install -g serverless

      # Step 4: Install dependencies
      - name: Install project dependencies
        run: npm install

      # Step 5: Lint the code (Optional)
      - name: Run linting
        run: npm run lint

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Deploy to AWS using Serverless Framework
      - name: Deploy to AWS
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: serverless deploy --verbose --stage staging

      # Step 8: Run post-deployment tests
      - name: Run post-deployment tests
        run: |
          echo "Testing deployed endpoints..."
          curl --fail https://i1kn2k2p83.execute-api.us-east-1.amazonaws.com/todos

      # Step 8: Roll back if failure
      - name: Rollback on failure
        if: failure()
        run: |
          echo "Rolling back to previous stable version..."
          git reset --hard HEAD~1
          npm install
          serverless deploy --verbose --stage staging
